### ISSUE TITLE
Any experiments about the load balancing loss?

### ISSUE THREAD

**Issue by exhyy** [pjlab-sys4nlp/llama-moe#69]
Hi Authors! Thanks for your excellent work!

I have a few questions about this paper:
1. Was the result in Table 2 obtained using `Independent-Random`?
2. I am surprised that `Independent-Random` achieves the best results. I am wandering if there are any relationships between the results and load balancing loss. Do you have any experiments about it? For example, using the random hashing layer in MoEBERT rather than a trainable router with load balancing loss.

**Comment by exhyy** [comment]
@Spico197 @DaizeDong

**Comment by Spico197** [comment]
Hi there, thanks for your attention to this project~
1. Yes the best results are obtained by `Independent-Random`
2. Since MoE-fy from dense models is not a common setting for MoE training, we kindly refer to Fig. 2 in [Wang et al. (2024)](https://arxiv.org/abs/2408.15664), which demonstrates that greater $\alpha$ values (lower balance loss) would result to worse perplexities.

**Comment by exhyy** [comment]
I see. Thanks for your explanations!
